#ifndef HTB_HARDWARE_INTERFACES__VISIBILITY_CONTROL_H_
#define HTB_HARDWARE_INTERFACES__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define HTB_HARDWARE_INTERFACES_EXPORT __attribute__((dllexport))
#define HTB_HARDWARE_INTERFACES_IMPORT __attribute__((dllimport))
#else
#define HTB_HARDWARE_INTERFACES_EXPORT __declspec(dllexport)
#define HTB_HARDWARE_INTERFACES_IMPORT __declspec(dllimport)
#endif
#ifdef HTB_HARDWARE_INTERFACES_BUILDING_DLL
#define HTB_HARDWARE_INTERFACES_PUBLIC HTB_HARDWARE_INTERFACES_EXPORT
#else
#define HTB_HARDWARE_INTERFACES_PUBLIC HTB_HARDWARE_INTERFACES_IMPORT
#endif
#define HTB_HARDWARE_INTERFACES_PUBLIC_TYPE HTB_HARDWARE_INTERFACES_PUBLIC
#define HTB_HARDWARE_INTERFACES_LOCAL
#else
#define HTB_HARDWARE_INTERFACES_EXPORT __attribute__((visibility("default")))
#define HTB_HARDWARE_INTERFACES_IMPORT
#if __GNUC__ >= 4
#define HTB_HARDWARE_INTERFACES_PUBLIC __attribute__((visibility("default")))
#define HTB_HARDWARE_INTERFACES_LOCAL __attribute__((visibility("hidden")))
#else
#define HTB_HARDWARE_INTERFACES_PUBLIC
#define HTB_HARDWARE_INTERFACES_LOCAL
#endif
#define HTB_HARDWARE_INTERFACES_PUBLIC_TYPE
#endif

#endif  // HTB_HARDWARE_INTERFACES__VISIBILITY_CONTROL_H_
